# Generated by Django 5.1.3 on 2025-05-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method_id',
        ),
    ]
