# Generated by Django 4.2.10 on 2025-06-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_platform_fee_order_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vat',
        ),
    ]
