# Generated by Django 4.2.10 on 2025-06-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_delivery_fee_remove_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subtotal',
            new_name='delivery_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
