# Generated by Django 4.2.1 on 2025-08-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("picked_up", "Picked Up"),
                    ("on_the_way", "On The Way"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                ],
                default="pending_pickup",
                max_length=20,
            ),
        ),
    ]
