# Generated by Django 5.1.3 on 2025-05-27 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'Product_Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(choices=[('kg', 'Kilogram'), ('piece', 'Piece'), ('bunch', 'Bunch'), ('litre', 'Litre'), ('bag', 'Bag')], default='kg', max_length=10)),
                ('is_perishable', models.BooleanField(default=True)),
                ('shelf_life_days', models.IntegerField(default=7)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
            options={
                'db_table': 'Products',
                'indexes': [models.Index(fields=['category'], name='Products_categor_40b2cd_idx'), models.Index(fields=['is_perishable'], name='Products_is_peri_b21e2d_idx')],
            },
        ),
    ]
