# Generated by Django 5.1.3 on 2025-05-27 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_available', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('quality_grade', models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('economy', 'Economy')], default='standard', max_length=10)),
                ('is_organic_certified', models.BooleanField(default=False)),
                ('listing_status', models.CharField(choices=[('available', 'Available'), ('pre_order', 'Pre-order'), ('sold_out', 'Sold Out'), ('inactive', 'Inactive')], default='available', max_length=15)),
                ('photos', models.JSONField(blank=True, default=list, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='products.product')),
            ],
            options={
                'db_table': 'Product_Listings',
                'indexes': [models.Index(fields=['farmer'], name='Product_Lis_farmer__ca14d5_idx'), models.Index(fields=['product'], name='Product_Lis_product_d7f4b4_idx'), models.Index(fields=['listing_status'], name='Product_Lis_listing_d0ec1d_idx'), models.Index(fields=['harvest_date'], name='Product_Lis_harvest_499e81_idx')],
            },
        ),
    ]
