# Generated by Django 4.2.10 on 2025-06-10 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.AutoField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(max_length=100, unique=True)),
                ('county_code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'db_table': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('sub_county_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_county_name', models.CharField(max_length=100)),
                ('sub_county_code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_counties', to='locations.county')),
            ],
            options={
                'verbose_name_plural': 'Sub Counties',
                'db_table': 'SubCounties',
                'unique_together': {('county', 'sub_county_name'), ('county', 'sub_county_code')},
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('location_name', models.CharField(help_text='e.g., Westlands, Karen, etc.', max_length=100)),
                ('detailed_address', models.TextField(help_text='Building, floor, apartment number, landmarks, etc.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.county')),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.subcounty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserAddresses',
                'indexes': [models.Index(fields=['user'], name='UserAddress_user_id_2a75ca_idx'), models.Index(fields=['county'], name='UserAddress_county__bd79af_idx'), models.Index(fields=['sub_county'], name='UserAddress_sub_cou_86e3ee_idx')],
            },
        ),
    ]
