# Generated by Django 4.2.10 on 2025-07-06 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('user_role', models.CharField(choices=[('customer', 'Customer'), ('farmer', 'Farmer'), ('rider', 'Rider'), ('all', 'All Users')], default='all', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_faqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order_index', 'created_at'],
                'indexes': [models.Index(fields=['user_role'], name='communicati_user_ro_fa08ef_idx'), models.Index(fields=['category'], name='communicati_categor_9cc30d_idx'), models.Index(fields=['is_active'], name='communicati_is_acti_116713_idx')],
            },
        ),
    ]
