# Generated by Django 4.2.10 on 2025-07-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_faq'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='faq',
            name='communicati_user_ro_fa08ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='faq',
            name='communicati_categor_9cc30d_idx',
        ),
        migrations.RemoveIndex(
            model_name='faq',
            name='communicati_is_acti_116713_idx',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='user_role',
        ),
        migrations.AddField(
            model_name='faq',
            name='target_role',
            field=models.CharField(choices=[('customer', 'Customer'), ('farmer', 'Farmer'), ('rider', 'Rider'), ('all', 'All Users')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order_index',
            field=models.IntegerField(default=0, help_text='Display order (lower numbers first)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
