# Generated by Django 4.2.1 on 2025-08-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communication", "0003_remove_faq_communicati_user_ro_fa08ef_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="related_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
