# Generated by Django 4.2.10 on 2025-07-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_subtotal_order_delivery_fee_and_more'),
        ('payments', '0002_paymenttransaction_callback_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order'),
        ),
    ]
