# Generated by Django 4.2.10 on 2025-07-06 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_subtotal_order_delivery_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_alter_paymenttransaction_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cart_snapshot', models.JSONField(help_text='Complete cart data at time of payment')),
                ('delivery_details', models.JSONField(help_text='Address, phone, instructions, etc.')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('session_status', models.CharField(choices=[('pending', 'Pending'), ('payment_initiated', 'Payment Initiated'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('order_created', 'Order Created')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Session expires 15 minutes after creation')),
            ],
            options={
                'verbose_name': 'Payment Session',
                'verbose_name_plural': 'Payment Sessions',
                'db_table': 'Payment_Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentsession'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment_session'], name='Payment_Tra_payment_05aa3e_idx'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_session', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['user'], name='Payment_Ses_user_id_5dccf2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['session_status'], name='Payment_Ses_session_23794e_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['expires_at'], name='Payment_Ses_expires_6178e8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsession',
            index=models.Index(fields=['created_at'], name='Payment_Ses_created_56f47b_idx'),
        ),
    ]
