# Generated by Django 4.2.10 on 2025-07-06 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentsession_and_more'),
    ]

    operations = [
    ]
