# Generated by Django 4.2.10 on 2025-06-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Phone number verification status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marketing_notifications',
            field=models.BooleanField(default=False, help_text='Receive marketing messages'),
        ),
        migrations.AddField(
            model_name='user',
            name='order_updates',
            field=models.BooleanField(default=True, help_text='Receive order status updates'),
        ),
        migrations.AddField(
            model_name='user',
            name='price_alerts',
            field=models.BooleanField(default=True, help_text='Receive price update alerts'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=True, help_text='Receive SMS notifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weather_alerts',
            field=models.BooleanField(default=True, help_text='Receive weather alerts (farmers only)'),
        ),
    ]
