# Generated by Django 5.1.3 on 2025-05-27 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=255)),
                ('total_acreage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('farm_description', models.TextField(blank=True, null=True)),
                ('farm_photos', models.JSONField(blank=True, default=list, null=True)),
                ('is_certified_organic', models.BooleanField(default=False)),
                ('weather_zone', models.CharField(choices=[('highland', 'Highland'), ('midland', 'Midland'), ('lowland', 'Lowland')], default='highland', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='locations.location')),
            ],
            options={
                'db_table': 'Farms',
                'indexes': [models.Index(fields=['farmer'], name='Farms_farmer__66c11d_idx'), models.Index(fields=['location'], name='Farms_locatio_9252ff_idx')],
            },
        ),
    ]
