# Generated by Django 4.2.10 on 2025-06-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='cultivated_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Area currently under cultivation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silt', 'Silt'), ('peaty', 'Peaty'), ('chalky', 'Chalky')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='water_source',
            field=models.CharField(blank=True, choices=[('borehole', 'Borehole'), ('river', 'River'), ('rain', 'Rain Water'), ('well', 'Well'), ('municipal', 'Municipal Supply'), ('dam', 'Dam')], max_length=10, null=True),
        ),
    ]
