# Generated by Django 4.2.10 on 2025-06-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_county_subcounty_useraddress'),
        ('farms', '0002_farm_cultivated_area_farm_soil_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='farm',
            name='Farms_locatio_9252ff_idx',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='location',
        ),
        migrations.AddField(
            model_name='farm',
            name='sub_county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='locations.subcounty'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['sub_county'], name='Farms_sub_cou_2b5e73_idx'),
        ),
    ]
