# Generated by Django 4.2.10 on 2025-07-05 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_county_subcounty_useraddress'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPlace',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(db_index=True, max_length=200)),
                ('place_type', models.CharField(choices=[('shopping', 'Shopping Center/Mall'), ('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('attraction', 'Tourist Attraction'), ('park', 'Park/Recreation'), ('business', 'Business District'), ('area', 'Residential/Commercial Area'), ('education', 'Educational Institution'), ('hospital', 'Hospital/Medical'), ('transport', 'Transport Hub'), ('government', 'Government Office'), ('religious', 'Religious Site'), ('other', 'Other')], default='other', max_length=20)),
                ('alternative_names', models.JSONField(blank=True, default=list, help_text='Alternative names/spellings for this place')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this place has been verified')),
                ('popularity_score', models.IntegerField(default=0, help_text='Higher score = more popular')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_places', to='locations.subcounty')),
            ],
            options={
                'db_table': 'PopularPlaces',
                'indexes': [models.Index(fields=['place_name'], name='PopularPlac_place_n_c8c581_idx'), models.Index(fields=['place_type'], name='PopularPlac_place_t_a1a60c_idx'), models.Index(fields=['sub_county'], name='PopularPlac_sub_cou_0aa2e4_idx'), models.Index(fields=['popularity_score'], name='PopularPlac_popular_3f723c_idx')],
                'unique_together': {('place_name', 'sub_county')},
            },
        ),
        migrations.CreateModel(
            name='AddressValidationCache',
            fields=[
                ('cache_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('detailed_address', models.TextField()),
                ('validation_result', models.JSONField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('sub_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.subcounty')),
            ],
            options={
                'db_table': 'AddressValidationCache',
                'indexes': [models.Index(fields=['address_hash'], name='AddressVali_address_5df938_idx'), models.Index(fields=['expires_at'], name='AddressVali_expires_bea764_idx')],
            },
        ),
    ]
