# Generated by Django 5.1.3 on 2025-05-27 12:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('product', 'Product'), ('farmer', 'Farmer'), ('rider', 'Rider')], max_length=10)),
                ('target_id', models.UUIDField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_photos', models.JSONField(blank=True, default=list)),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-review_date'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='feedback_re_target__d12921_idx'), models.Index(fields=['reviewer'], name='feedback_re_reviewe_cc9eed_idx'), models.Index(fields=['order_item'], name='feedback_re_order_i_52b4fc_idx')],
            },
        ),
    ]
