# Generated by Django 4.2.10 on 2025-06-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='target_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='target_type',
            field=models.CharField(choices=[('product', 'Product'), ('farmer', 'Farmer')], max_length=10),
        ),
    ]
